### ISSUE TITLE
✨ ゲームオブジェクトの基底クラスをまとめて処理を動かすクラスの作成

### ISSUE THREAD

**Issue by Harutaka-Tsujino** [human-osaka-game-2018/Summoners-Aster#13]
## 概要
登録されたゲームオブジェクトの更新、描画を一括で行うクラスの作成
## 背景と目的
ゲームオブジェクトをまとめて動かし管理を楽にする
## 最終的なゴール
オブジェクトの登録、更新、描画、解除を行うことができる
## 期限
2019/3/18
## 仕様
描画する際はオブジェクトのｚ値が遠い順に描画を行わせる
## 参考
#12

**Comment by rikita-fujizono** [comment]
#22 のコミットで実装してしまったのでこのissueは閉じます。
