### ISSUE TITLE
✨ 演出の追加

### ISSUE THREAD

**Issue by Harutaka-Tsujino** [human-osaka-game-2018/Summoners-Aster#70]
## 概要
様々な処理に楽しさと明確さを持たせるために演出を付与する
## 背景と目的
現状どういう処理が行われたかわかりにくいため
## 最終的なゴール
メインゲーム中のアクション全てにエフェクトをつける
## 期限
05/03

**Comment by taishi-matsumura** [comment]
操作に対する効果ももちろん大事なんですが、先日のプレゼンで指摘したように、戦略を練っているとき等の無操作時に「今どういう状態なのか」をわかりやすくするのはもっと大事ですよ。
特にカードゲームなどでは、操作している時間より画面を見ている時間の方が長いことが多いので、画面内の各オブジェクトのレイアウトや大きさや色合いが重要になってきますね！
